language: generic
dist: trusty
sudo: required
cache: apt
before_install:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
  - sudo apt-get install -y nodejs
  - sudo add-apt-repository ppa:kelleyk/emacs -y
  - sudo apt-get update
  - sudo apt-get remove emacs* -y
  - sudo apt-get install -y emacs25
  - emacs --version
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="/home/travis/.cask/bin:$PATH"
  - cask
install:
  - cask install
script:
  - ./run-lint.sh
  - ./run-tests.sh
